{% set name = "pycurl" %}
{% set version = "7.45.3" %}
{% set sha256 = "8c2471af9079ad798e1645ec0b0d3d4223db687379d17dd36a70637449f81d6b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/msvc_warnings.patch                     # [win]
    - patches/swap_bottle_for_flask.patch

build:
  number: 0
  detect_binary_files_with_prefix: False
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - openssl    # [win]
    - m2-patch   # [win]
    - patch      # [unix]
  host:
    - openssl {{ openssl }}   # [not win]
    - python
    - libcurl 7.88.1
    - setuptools
    - wheel
    - pip
  run:
    - python
    - openssl 3.*

test:
  requires:
    - pip
    # Running unit tests requires bottle, using flask instead via patch file.
    - pytest >=5
    - flask
    - flaky
    - pyflakes
  source_files:
    - pytest.ini
    - README.rst
    - setup.py
    - tests
  commands:
    - pip check
    # Skip tests for SSL backends we don't support.
    - pytest -v tests -k "not (test_keyfunction or test_proxy_tlsauth or test_libcurl_ssl_gnutls or test_libcurl_ssl_nss or test_libcurl_ssl_openssl)"

about:
  home: http://pycurl.io/
  license: LGPL-2.1-or-later OR MIT
  license_file:
    - COPYING-LGPL
    - COPYING-MIT
  license_family: LGPL
  summary: A Python Interface To The cURL library
  description: |
    PycURL is a Python interface to libcurl, the multiprotocol file transfer library.
    Similarly to the urllib Python module, PycURL can be used to fetch objects identified
    by a URL from a Python program.
  doc_url: http://pycurl.io/docs/latest/index.html
  dev_url: https://github.com/pycurl/pycurl

extra:
  skip-lints:
    - http_url
  recipe-maintainers:
    - chrisburr
