{% set name = "pycurl" %}
{% set version = "7.46.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 422ed7005b98768fe60fe6b6cb8bb6a4e1fc18b5433402e8fbdaba91811c4604

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - openssl  # [win]
  host:
    - pip
    - python
    - setuptools >=77
    - wheel
    - libcurl {{ libcurl }}
    - openssl {{ openssl }}
  run:
    - python
    - libcurl
    - openssl

test:
  source_files:
    - tests
    - pytest.ini
    - README.rst
    - setup.py
  imports:
    - pycurl
  requires:
    - {{ stdlib('c') }}  # [not win]
    - {{ compiler('c') }}  # [not win]
    - make  # [not win]
    - pip
    - pytest >=5
    - flask
    - flaky
    - numpy
    - pyflakes
    # For tests/setup_test.py
    - setuptools
    - websockets >=12.0
  commands:
    - pip check

about:
  home: http://pycurl.io
  license: LGPL-2.1-only OR MIT
  license_file:
    - COPYING-LGPL
    - COPYING-MIT
  license_family: LGPL
  summary: A Python Interface To The cURL library
  description: |
    PycURL is a Python interface to libcurl, the multiprotocol file transfer library.
    Similarly to the urllib Python module, PycURL can be used to fetch objects identified
    by a URL from a Python program.
  doc_url: http://pycurl.io/docs/latest/index.html
  dev_url: https://github.com/pycurl/pycurl

extra:
  skip-lints:
    - http_url
  recipe-maintainers:
    - chrisburr
