{% set name = "pycurl" %}
{% set version = "7.45.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d43013002eab2fd6d0dcc671cd1e9149e2fc1c56d5e796fad94d076d6cb69ef

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - openssl  # [win]
  host:
    - pip
    - python
    - setuptools
    - wheel
    - libcurl {{ libcurl }}
    - openssl {{ openssl }}
  run:
    - python
    - openssl

test:
  source_files:
    - tests
    - pytest.ini
    - README.rst
    - setup.py
  requires:
    - {{ stdlib('c') }}  # [not win]
    - {{ compiler('c') }}  # [not win]
    - make  # [not win]
    - pip
    - pytest >=5
    - flask
    - flaky
    - pyflakes

about:
  home: http://pycurl.io
  license: LGPL-2.1-or-later OR MIT
  license_file:
    - COPYING-LGPL
    - COPYING-MIT
  license_family: LGPL
  summary: A Python Interface To The cURL library
  description: |
    PycURL is a Python interface to libcurl, the multiprotocol file transfer library.
    Similarly to the urllib Python module, PycURL can be used to fetch objects identified
    by a URL from a Python program.
  doc_url: http://pycurl.io/docs/latest/index.html
  dev_url: https://github.com/pycurl/pycurl

extra:
  skip-lints:
    - http_url
  recipe-maintainers:
    - chrisburr
